version: '3'
services:

  app:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    tty: true
    networks:
      - app-network
    volumes:
      - ./app:/var/www
    environment:
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_URL: ${NGINX_HOST}
  nginx:
    image: nginx:alpine
    tty: true
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${NGINX_PORT}:80"
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
    networks:
      - app-network
  db:
    image: postgres:13-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network
  redis:
    image: redis:6.0.5
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    volumes:
      - ./redis_data:/data

networks:
  app-network:
    driver: bridge
